---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nwapp-ingress
  labels:
    app: northwind
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: "v1.nwapp.167.172.6.182.nip.io"
    http:
        paths:
        - path: /
          backend:
            serviceName: nwapp-svc
            servicePort: 80
  - host: "v2.nwapp.167.172.6.182.nip.io"
    http:
        paths:
        - path: /
          backend:
            serviceName: nwappv2-svc
            servicePort: 80
