---
apiVersion: v1
kind: Namespace
metadata:
  name: myns
  labels:
    dept: pd
---
apiVersion: v1
kind: Pod
metadata:
  name: fortune-pod
  namespace: myns
  labels:
    dept: pd 
    app: fortune
spec:
  containers:
  - name: fortune-container
    image: chukmunnlee/fortune:v1
    imagePullPolicy: IfNotPresent
    env:
    - name: APP_PORT
      value: "8080"
    ports:
    - name: fortune-port
      containerPort: 8080
