---
# fortune deployment with istio sidecar injected
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortune-deploy
  labels:
    app: myapp
    dept: pd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fortune-pod
      dept: pd
  template:
    metadata:
      name: fortune-pod
      labels:
        dept: pd
        app: fortune-pod
    spec:
      containers:
      - name: fortune-container
        image: chukmunnlee/fortune:v1
        imagePullPolicy: IfNotPresent
        ports:
        - name: http-port
          containerPort: 3000
