---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nwapp-cm
  labels:
    app: northwind
data:
  DB_USER: root
  DB_HOST: nwdb-mysql-master.nwapp.svc.cluster.local  # changed to mysql-cluster ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nwapp-deploy
  labels:
    app: northwind
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nwapp-pod
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      name: nwapp-pod
      labels:
        app: nwapp-pod
    spec:
      containers:
      - name: nwapp-container
        image: chukmunnlee/nwapp:v1 
        imagePullPolicy: IfNotPresent
        resources:
            requests:
              cpu: 100m
        env:
        - name: APP_PORT
          value: "3000"
        - name: INSTANCE_IP_ADDRESS
          valueFrom:
              fieldRef:
                fieldPath: status.podIP
        - name: DB_USER
          valueFrom:
              configMapKeyRef:
                name: nwapp-cm
                key: DB_USER
        - name: DB_HOST
          valueFrom:
              configMapKeyRef:
                name: nwapp-cm
                key: DB_HOST
        - name: DB_PASSWORD
          valueFrom:
              secretKeyRef:
                name: nwdb-cluster-secret # Reference cluster secret
                key: ROOT_PASSWORD
        ports:
        - name: http-port
          containerPort: 3000
        livenessProbe:
            httpGet:
              port: http-port
              path: /health
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: nwapp-svc
  labels:
    app: northwind
spec:
  type: ClusterIP
  selector:
    app: nwapp-pod
  ports:
  - name: app-port
    port: 80 
    targetPort: http-port
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nwapp-ingress
  labels:
    app: northwind
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: "nwapp.167.172.6.182.nip.io"
    http:
        paths:
        - path: /
          backend:
            serviceName: nwapp-svc
            servicePort: app-port

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nwapp-hpa
  labels:
    app: northwind
spec:
  minReplicas: 2
  maxReplicas: 7
  targetCPUUtilizationPercentage: 20
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nwapp-deploy
