---
apiVersion: v1
kind: Secret
metadata:
  name: nwdb-secret
  labels:
    app: northwind
data:
  MYSQL_ROOT_PASSWORD: Y2hlY2tpdA==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nwdb-deploy
  labels:
    app: northwind
spec:
  replicas: 1
  selector:
    matchLabels:
      app: northwind-pod
  template:
    metadata:
      name: nwdb-pod
      labels:
        app: northwind-pod
    spec:
      containers:
      - name: nwdb-container
        image: chukmunnlee/nwdb:v3
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nwdb-secret
              key:  MYSQL_ROOT_PASSWORD
        livenessProbe:
          exec:
            command:
            - bash
            - -c
            - "mysqladmin ping -uroot -p${MYSQL_ROOT_PASSWORD} || exit 1"
          periodSeconds: 30
          timeoutSeconds: 60
          initialDelaySeconds: 40
          failureThreshold: 3
        ports:
        - name: mysql-port
          containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: nwdb-svc
  labels:
    app: northwind
spec:
  selector:
    app: northwind-pod
  type: ClusterIP
  ports:
  - name: db-port
    port: 3306
    targetPort: mysql-port
